/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: martinjario (https://sketchfab.com/martinjario)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
Title: Skull downloadable
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";

export function Skull(props: any) {
  //TODO: Finish implementing mouse tracking
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  useEffect(() => {
    addEventListener("mousemove", (e) => {
      console.log("X: ", e.clientX, " Y: ", e.clientY);
      setMousePosition({ x: e.clientX, y: e.clientY });
    });
    return () => removeEventListener("mousemove", () => {});
  }, []);

  const { nodes, materials } = useGLTF("/skull/scene.gltf");
  const ref = useRef({ rotation: { x: 0, y: 0 } });
  useFrame((state, delta) => {
    ref.current.rotation.x += delta;
    ref.current.rotation.y += delta;
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.defaultMat}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/skull_downloadable/scene.gltf");
