/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: martinjario (https://sketchfab.com/martinjario)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
Title: Skull downloadable
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";

export function Skull(props: any) {
  const [isHovering, setIsHovering] = useState(false);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  useEffect(() => {
    addEventListener("mousemove", (e) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
    });
    return () => removeEventListener("mousemove", () => {});
  }, []);

  const calculateRotation = (position: number, boundarySize: number) => {
    const middle = boundarySize / 2;
    if (position < middle) {
      return position / middle - 1;
    } else if (position > middle) {
      return (position - middle) / (boundarySize - middle);
    }
    return 0;
  };

  const { nodes, materials } = useGLTF("/skull/scene.gltf");
  const ref = useRef({ rotation: { x: 0, y: 0, z: 0 } });
  useFrame((state, delta) => {
    ref.current.rotation.z = calculateRotation(
      mousePosition.x,
      window.innerWidth
    );
    ref.current.rotation.x =
      calculateRotation(mousePosition.y, window.innerHeight) - Math.PI / 2;
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        onPointerEnter={() => setIsHovering(true)}
        onPointerLeave={() => setIsHovering(false)}
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.defaultMat}
      />
    </group>
  );
}

useGLTF.preload("/skull_downloadable/scene.gltf");
